Fix: More updates to bootstrap GHA workflow
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/bootstrap.yaml b/.github/workflows/bootstrap.yaml
--- a/.github/workflows/bootstrap.yaml
+++ b/.github/workflows/bootstrap.yaml
@@ -30,19 +30,22 @@ jobs:
           repository: "os-climate/devops-toolkit"
           path: ".devops"
 
-      - name: "Purge this working branch, if necessary"
-        id: remove-branch
-        continue-on-error: true
-        # Remove update-devops-tooling branch, if it exists
-        run: |
-          git branch -d update-devops-tooling || :
-          git push origin --delete update-devops-tooling || :
-
       - name: "Update repository workflows and create PR"
         env:
           GH_TOKEN: ${{ github.token }}
         run: |
           ### SHELL CODE START ###
+
+          REPO_DIR=$(git rev-parse --show-toplevel)
+          # Ensure working from top-level of GIT repository
+          CURRENT_DIR=$(pwd)
+          if [ "$REPO_DIR" != "$CURRENT_DIR" ]; then
+              echo "Changing directory to: $REPO_DIR"
+              if ! (cd "$REPO_DIR"); then
+                  echo "Error: unable to change directory"; exit 1
+              fi
+          fi
+
           # Define a function to allow selective opt-out of devops tooling
           OPT_OUT=".devops-exclusions"
           perform_operation() {
@@ -63,8 +66,13 @@ jobs:
           }
 
           # Remove update-devops-tooling branch if it exists
-          git branch -d update-devops-tooling || true
-          git push origin --delete update-devops-tooling || true
+          # Remove branch, if it exists: update-devops-tooling
+          if (git rev-parse --verify update-devops-tooling > /dev/null); then
+            git branch -d update-devops-tooling
+          elif (git ls-remote origin update-devops-tooling); then
+            echo "Removing remote branch: update-devops-tooling"
+            git push origin --delete update-devops-tooling
+          fi
           git checkout -b "update-devops-tooling"
 
           # Configure GIT
@@ -112,6 +120,7 @@ jobs:
             git commit -m \
               "Chore: Update DevOps tooling from central repository [skip-ci]"
             git push --set-upstream origin update-devops-tooling
+            # ToDo: need to verify if we are running in a GHA
             gh pr create --title \
               "Chore: Pull DevOps tooling from upstream repository" \
               --body 'Automated by a GitHub workflow: bootstrap.yaml'
