Fix: Better error handling
Signed-off-by: Matthew Watkins <mwatkins@linuxfoundation.org>

diff --git a/.github/workflows/bootstrap.yaml b/.github/workflows/bootstrap.yaml
--- a/.github/workflows/bootstrap.yaml
+++ b/.github/workflows/bootstrap.yaml
@@ -65,7 +65,6 @@ jobs:
             fi
           }
 
-          # Remove update-devops-tooling branch if it exists
           # Remove branch, if it exists: update-devops-tooling
           if (git rev-parse --verify update-devops-tooling > /dev/null); then
             git branch -d update-devops-tooling
@@ -117,12 +116,23 @@ jobs:
             echo "No updates/changes to commit"; exit 0
           else
             git add .
-            git commit -m \
-              "Chore: Update DevOps tooling from central repository [skip-ci]"
-            git push --set-upstream origin update-devops-tooling
-            # ToDo: need to verify if we are running in a GHA
-            gh pr create --title \
-              "Chore: Pull DevOps tooling from upstream repository" \
-              --body 'Automated by a GitHub workflow: bootstrap.yaml'
+            if ! (git commit -m \
+              "Chore: Update DevOps tooling from central repository [skip-ci]\n\nCreated by automation"); then
+              echo "Commit failed; deleting local and remote branches"
+              git checkout main
+              # Remove branch, if it exists: update-devops-tooling
+              if (git rev-parse --verify update-devops-tooling > /dev/null); then
+                  git branch -d update-devops-tooling
+              elif (git ls-remote origin update-devops-tooling); then
+                  echo "Removing remote branch: update-devops-tooling"
+                  git push origin --delete update-devops-tooling
+              fi
+            else
+              git push --set-upstream origin update-devops-tooling
+              # ToDo: need to verify if we are running in a GHA
+              gh pr create --title \
+                "Chore: Pull DevOps tooling from upstream repository" \
+                --body 'Automated by a GitHub workflow: bootstrap.yaml'
+            fi
           fi
           ### SHELL CODE END ###
